
# Site settings
title: The Revenue CISO
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://RevenueCISO.com" 

collections:
  articles:
    output: true
    permalink: /articles/:path/
    sort_by: order
    
  packages:
    output: true
    permalink: /packages/:path/
    sort_by: order



# Markdown settings
markdown: kramdown

# Sass settings
# sass:
#   add_charset: true
#   sass_dir: assets/sass
#   style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap